# db:
#   host: postgres
#   port: 5432
#   user: postgres
#   password: postgres
#   name: subscriptions_db
# # receipt-analyzer:
# #   port: 8080


db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: subscriptions_db
