# db:
#   host: postgres
#   port: 5432
#   user: postgres
#   password: postgres
#   name: subscriptions_db

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: subscriptions_db
